[package]
name = "captrs"
version = "0.2.1"
authors = ["bryal <96.bryal@gmail.com>"]

description = "Cross-platform screen capture lib"
repository = "https://github.com/bryal/captrs"
readme = "README.md"
keywords = ["Windows", "Linux", "screen", "record", "capture"]
license = "MIT"

[dependencies]
dxgcap = "0.0.8"
x11cap = "0.4.1"

[dev-dependencies]
shuteye = "0.2"
